// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjtFCwW1Jes2fxwjYqMC2ibPBEqCR5mIM',
    appId: '1:1093116072279:web:348101abdf72d932af6e12',
    messagingSenderId: '1093116072279',
    projectId: 'cf8tpr1nt',
    authDomain: 'cf8tpr1nt.firebaseapp.com',
    storageBucket: 'cf8tpr1nt.appspot.com',
    measurementId: 'G-HSYNL65MMD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpd28xgqePDVIIVs044eB077qILJoLKq4',
    appId: '1:1093116072279:android:69d32fd3aee1873faf6e12',
    messagingSenderId: '1093116072279',
    projectId: 'cf8tpr1nt',
    storageBucket: 'cf8tpr1nt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA37J64WjIF_XpaQpGewgV79ZpKXLpn2Js',
    appId: '1:1093116072279:ios:b4d30373a3001853af6e12',
    messagingSenderId: '1093116072279',
    projectId: 'cf8tpr1nt',
    storageBucket: 'cf8tpr1nt.appspot.com',
    iosClientId:
        '1093116072279-t88l9cg3utefoss5crkk4bgqlg60rl7f.apps.googleusercontent.com',
    iosBundleId: 'com.example.cf8tpr1nt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA37J64WjIF_XpaQpGewgV79ZpKXLpn2Js',
    appId: '1:1093116072279:ios:b4d30373a3001853af6e12',
    messagingSenderId: '1093116072279',
    projectId: 'cf8tpr1nt',
    storageBucket: 'cf8tpr1nt.appspot.com',
    iosClientId:
        '1093116072279-t88l9cg3utefoss5crkk4bgqlg60rl7f.apps.googleusercontent.com',
    iosBundleId: 'com.example.cf8tpr1nt',
  );
}
